version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: cve_postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: always

  api:
    image: cve_api
    container_name: cve_api
    volumes:
      - .:/app
    build:
      context: .
    env_file:
      - .env
    ports:
      - 8000:8000
    command: gunicorn app:app -b 0.0.0.0:8000 --worker-class uvicorn.workers.UvicornWorker
  