version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: cve_postgres
    env_file:
      - .env
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#      POSTGRES_DB: app
    ports:
      - "5432:5432"
    restart: always
